### ISSUE TITLE
Theme settings example only build locally

### ISSUE THREAD

**Issue by gvolpe** [styx-static/styx-theme-agency#1]
The theme is set to the relative directory and is using `generic-templates` instead. Is that intentional?

```nix
  themes = [
    styx-themes.generic-templates
    ../.
  ];
```

I'm trying to set it up as follows using `styx-0.7.2`:

```nix
  themes = [
    styx-themes.agency
  ];
```

But I get the following error:

```
error: attribute 'layout' missing, at /nix/store/5glgi1csnkmzp5fbvm6mcz5i950k4dii-styx-0.7.2-lib/generation.nix:57:22
(use '--show-trace' to show detailed location information)
```

I picked the same configuration described here: https://styx-static.github.io/styx-site/documentation/styx-themes.html#agency , which also seems wrong.

Not sure if the project is still maintained but I would love to give it a try. Thanks :)

**Comment by blaggacao** [comment]
This theme depends on the generic templates; you need to do:

```nix
{
  themes = [
    styx-themes.generic-templates
    styx-themes.agency
  ];
}
```

Your first example is the `/examples/site.nix` which can do the relative import.
